### ISSUE TITLE
Case troubles: angry tortoises

### ISSUE THREAD

**Issue by llondon6** [llondon6/nrutils_dev#51]
I am creating this issue to catalog a case trouble that I've seen with `gwylm`'s `load_dynamics`.

The code state of interest is after the recent merge request with tortoise_coordinate and dynamics loading fixes: https://github.com/llondon6/nrutils_dev/commit/97615f746b3eb71e158645ab178eb8e575ac27ba

Note that this code state may be needed to access BAM NR data after their move to the super-computing wales facilities:
https://github.com/llondon6/nrutils_dev/commit/1b12671f0961a223b058dab02516582a67689fad

I have started a branch that includes the fixes to access BAM from super-computing wales, but does not includes changes related to tortoise_coordinate and dynamics loading:
https://github.com/llondon6/nrutils_dev/tree/before_the_rain

I am preparing a notebook to demonstrate the case issue.

**Comment by llondon6** [comment]
I've started a branch for this issue here: https://github.com/llondon6/nrutils_dev/tree/issue51

**Comment by llondon6** [comment]
And @thompsonphys I've placed a notebook showing the case of interest here: https://github.com/llondon6/nrutils_dev/blob/issue51/issues/open/issue51.ipynb

**Comment by thompsonphys** [comment]
I _think_ that this issue arises because I added the new `radius_map_tortoise` key for the `extraction_map_dict` in the `bam.py` handler, and this dictionary is specified when the `scentry` element is generated. The key is required when using `load_dynamics` with the tortoise flag set. Since `scsearch` only loads previously-constructed scentry objects from the database, this flag will be missing if the catalog database hasn't been re-generated recently after theses changes were made. That should also explain why things work when using `simdir2scentry`, as the scentry object is created from scratch.

**Comment by thompsonphys** [comment]
Link to the specific scentry element change:
https://github.com/llondon6/nrutils_dev/blob/issue51/nrutils/handlers/bam.py#L516
